#!/usr/bin/env node
/**
 * generate-course.mjs
 *
 * Reads manifest.json and lesson .ts files to deterministically generate course.ts.
 * Replaces fragile regex-based patching with clean codegen.
 *
 * Usage:
 *   node scripts/generate-course.mjs
 *   make generate-course
 */

import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const courseDir = resolve(projectRoot, 'src/data/course/en')

export function generateCourse() {
  const manifest = JSON.parse(readFileSync(resolve(courseDir, 'manifest.json'), 'utf8'))

  // Read each lesson file to extract metadata
  const lessons = manifest.lessons.map((filePath) => {
    const fullPath = resolve(courseDir, filePath + '.ts')
    let content
    try {
      content = readFileSync(fullPath, 'utf8')
    } catch {
      throw new Error(`Lesson file not found: ${filePath}.ts`)
    }

    const exportMatch = content.match(/export const (\w+)/)
    if (!exportMatch) throw new Error(`No export found in ${filePath}.ts`)
    const templateVar = exportMatch[1]

    // Strip Template / _template suffix to get the materialized variable name
    const lessonVar = templateVar.replace(/[_]?[Tt]emplate$/, '')
    if (lessonVar === templateVar) {
      throw new Error(
        `Export '${templateVar}' in ${filePath}.ts must end with 'Template' or '_template'`
      )
    }

    const idMatch = content.match(/id:\s*'([^']+)'/)
    if (!idMatch) throw new Error(`No id field found in ${filePath}.ts`)
    const lessonId = idMatch[1]

    const unitIdMatch = content.match(/unitId:\s*'([^']+)'/)
    if (!unitIdMatch) throw new Error(`No unitId field found in ${filePath}.ts`)
    const unitId = unitIdMatch[1]

    return { filePath, templateVar, lessonVar, lessonId, unitId }
  })

  // Build unit map preserving manifest order
  const unitTitleMap = new Map(manifest.units.map((u) => [u.id, u.title]))
  const unitOrder = []
  const unitLessonsMap = new Map()

  // Seed from manifest.units order
  for (const u of manifest.units) {
    unitOrder.push(u.id)
    unitLessonsMap.set(u.id, [])
  }

  // Assign lessons to units (create unit entry if somehow missing from manifest)
  for (const lesson of lessons) {
    if (!unitLessonsMap.has(lesson.unitId)) {
      unitOrder.push(lesson.unitId)
      unitLessonsMap.set(lesson.unitId, [])
    }
    unitLessonsMap.get(lesson.unitId).push(lesson)
  }

  // ── Generate course.ts ──────────────────────────────────────────────────────

  const L = [] // output lines

  L.push(`// Auto-generated by scripts/generate-course.mjs — do not edit manually`)
  L.push(`// To modify, update manifest.json and run: make generate-course`)
  L.push(`import type { CourseData, LessonMapNode } from '@/core/lesson-engine/types'`)

  for (const l of lessons) {
    L.push(`import { ${l.templateVar} } from '@/data/course/en/${l.filePath}'`)
  }

  L.push(`import { extractLessonLexiconInventory, materializeLesson } from '@/data/lexicon'`)
  L.push(``)

  for (const l of lessons) {
    L.push(`const ${l.lessonVar} = materializeLesson(${l.templateVar})`)
  }

  if (lessons.length > 0) {
    L.push(
      `export const lessonLexiconInventory = extractLessonLexiconInventory(${lessons[0].templateVar})`
    )
  } else {
    // Keep a valid export even with 0 lessons so named imports don't break
    L.push(`export const lessonLexiconInventory = {}`)
  }

  L.push(``)

  // courseEn
  L.push(`export const courseEn: CourseData = {`)
  L.push(`  id: 'tupi-proto',`)
  L.push(`  language: 'en',`)
  L.push(`  units: [`)

  for (const unitId of unitOrder) {
    const unitLessons = unitLessonsMap.get(unitId) || []
    if (unitLessons.length === 0) continue // skip empty units
    const title = (unitTitleMap.get(unitId) || unitId).replace(/'/g, "\\'")
    L.push(`    {`)
    L.push(`      id: '${unitId}',`)
    L.push(`      title: '${title}',`)
    L.push(`      lessons: [${unitLessons.map((l) => l.lessonVar).join(', ')}],`)
    L.push(`    },`)
  }

  L.push(`  ],`)
  L.push(`}`)
  L.push(``)

  // pathNodesSeed — one node per lesson, in manifest order
  L.push(`export const pathNodesSeed: LessonMapNode[] = [`)

  lessons.forEach((l, i) => {
    const y = i * 96
    const x = i === 0 ? 0 : i % 2 === 0 ? 18 : -28
    L.push(`  {`)
    L.push(`    id: 'node-${i + 1}',`)
    L.push(`    unitId: '${l.unitId}',`)
    L.push(`    lessonId: '${l.lessonId}',`)
    L.push(`    x: ${x},`)
    L.push(`    y: ${y},`)
    L.push(`    type: 'lesson',`)
    L.push(`    unlocked: ${i === 0 ? 'true' : 'false'},`)
    L.push(`    completed: false,`)
    L.push(`  },`)
  })

  L.push(`]`)
  L.push(``)

  // lessonById
  L.push(`export const lessonById = new Map(`)
  L.push(
    `  courseEn.units.flatMap((unit) => unit.lessons.map((lesson) => [lesson.id, lesson] as const)),`
  )
  L.push(`)`)
  L.push(``)

  writeFileSync(resolve(courseDir, 'course.ts'), L.join('\n'))

  // Return summary for callers
  const activeUnits = unitOrder.filter((id) => (unitLessonsMap.get(id) || []).length > 0)
  return { lessons, unitOrder: activeUnits }
}

// ── CLI entry point ─────────────────────────────────────────────────────────

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const RESET = '\x1b[0m'
  const GREEN = '\x1b[32m'

  const result = generateCourse()
  console.log(
    `${GREEN}✓${RESET} Generated course.ts — ${result.lessons.length} lesson(s), ${result.unitOrder.length} unit(s)`
  )
}
