import type { EnToTupiMap } from '@/data/lexicon/types'

// Auto-generated by `make generate-englishtotupi-map`.
// Fill values with Tupi translations. Empty strings mean "pending translation".
// Keys default to "en:<normalized_term_or_phrase>" unless explicitly set in lesson data.
export const enToTupiMap: EnToTupiMap = {
  'en:coffee': 'kapery', // coffee
  'en:coffee_or_tea': "kapery konipó ka'ary", // Coffee or tea?
  'en:i_want_coffee': "a'useî kapery", // I want coffee.
  'en:i_want_tea': "a'useî ka'ary", // I want tea.
  'en:i_want_water': "a'useî 'y", // I want water.
  'en:milk': "kamby", // milk
  'en:or': 'konipó', // or
  'en:please': 'nde angaturama resé', // please
  'en:sugar': "takûare'ẽypy'oka", // sugar
  'en:tea': "ka'ary", // tea
  'en:tea_or_coffee': "ka'ary konipó kapery", // Tea or coffee?
  'en:thank_you': 'orokugûab', // Thank you.
  'en:water': "'y", // water
  'en:welcome': 'Eîkobé', // Welcome

  // Manual/legacy keys not currently referenced by lessons:
  'en:coffee_please': 'kapery, nde angaturama resé', // Coffee, please.
  'en:tea_please': "ka'ary, nde angaturama resé", // Tea, please.
  'en:water_please': "'y, nde angaturama resé", // Water, please.
  'en:thank': 'kugûab', // Thank
  'en:you': 'oro',
}

