import type { LessonTemplateData } from '@/core/lesson-engine/template-types'
import { repoAudio } from '@/data/audio/repoAudio'

// Generated by Tupi Trail Lesson Builder
// Lesson: Tembi'u
// Exported: 2026-03-27T15:59:42.293Z

export const unit1_tembi_u_template: LessonTemplateData = {
  id: 'unit1-tembi-u',
  unitId: 'unit1',
  title: 'Tembi\'u',
  subtitle: 'Tembi\'u îakaru ',
  estimatedMinutes: 5,
  exercises: [
    {
      id: 'ex1',
      type: 'select_image',
      instruction: 'Selecione a imagem correta',
      newWordBadge: true,
      character: { id: 'bird', mood: 'encouraging' },
      audio: repoAudio('audio/unit1-tembi-u/_word_tembi_u.webm', { id: '_word_tembi_u' }),
      slowAudio: repoAudio('audio/unit1-tembi-u/ex1-slow.webm', { id: 'ex1-slow' }),
      meaning: 'Comida',
      xp: 8,
      explanation: {
        grammarNotes: [
          { label: 't-', text: 'prefixo genérico de gente; quer dizer que não é de ninguém em particular, mas toda gente em geral.' },
          { label: '-embi-', text: 'Prefixo para falar sobre o paciente (objeto) de um verbo. "O que é ...-ado", neste caso com o verbo \'u (comer) significa literalmente "Aquilo que é comido" ou simplesmente em Português "a comida"' },
          { label: '\'u', text: 'ingerir; comer; beber' }
        ]
      },
      prompt: 'Tembi\'u ',
      options: [
        { id: 'leite', label: 'Kamby', imageEmoji: '🥛' },
        { id: 'café', label: 'Kapery', imageEmoji: '☕' },
        { id: 'água', label: '\'Y', imageEmoji: '💧' },
        { id: 'comida', label: 'Tembi\'u ', imageEmoji: '🍛' }
      ],
      correctOptionId: 'comida',
    },
    {
      id: 'ex2',
      type: 'select_image',
      instruction: 'Selecione a imagem correta',
      newWordBadge: true,
      character: { id: 'woman', mood: 'encouraging' },
      audio: repoAudio('audio/unit1-tembi-u/_word_apykaba.webm', { id: '_word_apykaba' }),
      slowAudio: repoAudio('audio/unit1-tembi-u/ex2-slow.webm', { id: 'ex2-slow' }),
      meaning: 'Cadeira',
      xp: 8,
      explanation: {
        grammarNotes: [
          { label: 'apyk', text: 'variação de "gûapyk (sentar-se)" que aparece em substantivo' },
          { label: '-aba', text: 'sufixo que fala de circunstâncias ao redor do verbo que modifica; o lugar/instrument/tempo/modo de fazer X." Neste case, "o lugar/instrumento de sentar-se" que em Português é um "assento" (uma cadeira)' }
        ]
      },
      prompt: 'Apykaba',
      options: [
        { id: 'boca', label: 'Îuru', imageEmoji: '👄' },
        { id: 'cadeira', label: 'Apykaba', imageEmoji: '🪑' },
        { id: 'comida', label: 'Tembi\'u ', imageEmoji: '🍛' },
        { id: 'colher', label: 'Pesẽ', imageEmoji: '🥄' }
      ],
      correctOptionId: 'cadeira',
    },
    {
      id: 'ex3',
      type: 'select_image',
      instruction: 'Selecione a imagem correta',
      newWordBadge: true,
      character: { id: 'man', mood: 'encouraging' },
      audio: repoAudio('audio/unit1-tembi-u/_word_pese.webm', { id: '_word_pese' }),
      slowAudio: repoAudio('audio/unit1-tembi-u/ex3-slow.webm', { id: 'ex3-slow' }),
      meaning: 'Colher',
      xp: 8,
      prompt: 'Pesẽ',
      options: [
        { id: 'colher', label: 'Pesẽ', imageEmoji: '🥄' },
        { id: 'café', label: 'Kapery', imageEmoji: '☕' },
        { id: 'cadeira', label: 'Apykaba', imageEmoji: '🪑' },
        { id: 'cha', label: 'Ka\'ary', imageEmoji: '🍵' }
      ],
      correctOptionId: 'colher',
    },
    {
      id: 'ex4',
      type: 'token_translate',
      instruction: 'Traduza esta frase',
      character: { id: 'bird', mood: 'thinking' },
      audio: repoAudio('audio/unit1-tembi-u/ex4-audio.webm', { id: 'ex4-audio' }),
      meaning: 'Quero comer comida',
      xp: 8,
      sourceText: [
        { text: 'A\'useî tembi\'u' }
      ],
      tokenBank: ['água', 'comida', 'beber', 'quero', 'comer'],
      correctSequence: ['quero', 'comer', 'comida'],
    },
    {
      id: 'ex5',
      type: 'token_translate',
      instruction: 'Traduza esta frase',
      newWordBadge: true,
      character: { id: 'man', mood: 'neutral' },
      audio: repoAudio('audio/unit1-tembi-u/ex5-audio.webm', { id: 'ex5-audio' }),
      meaning: 'Sento na cadeira',
      xp: 8,
      explanation: {
        grammarNotes: [
          { label: 'a-', text: 'eu; conjugação da primeira pessoa' },
          { label: 'gûapyk', text: 'sentar-se;' },
          { label: 'apyk', text: 'outra forma de "gûapyk (sentar-se)" que aparece em substantivos' },
          { label: '-aba', text: 'sufixo que nominaliza um verbo; lugar/instrument/modo/etc.' },
          { label: '-pe', text: 'partícula locativa; significa "em, na, no"' },
          { label: '-ápe', text: 'contração de "-aba" + "-pe"; quer dizer "no lugar/instrumento de..."' },
          { label: 'apykápe', text: 'no lugar de sentar-se; na cadeira' }
        ]
      },
      sourceText: [
        { text: 'agûapyk', highlight: 'new-word' },
        { text: 'apykápe' }
      ],
      promptSegments: [
        { text: 'agûapyk', highlight: 'new-word' }
      ],
      tokenBank: ['mesa', 'colher', 'sento', 'comida', 'na', 'cadeira'],
      correctSequence: ['sento', 'na', 'cadeira'],
    },
    {
      id: 'ex7',
      type: 'token_translate',
      instruction: 'Traduza esta frase',
      newWordBadge: true,
      character: { id: 'man', mood: 'neutral' },
      audio: repoAudio('audio/unit1-tembi-u/_word_ixe_aiporu.webm', { id: '_word_ixe_aiporu' }),
      meaning: 'Eu uso a colher',
      xp: 8,
      sourceText: [
        { text: 'IXÉ AÎPORU', highlight: 'new-word' },
        { text: 'pesẽ' }
      ],
      promptSegments: [
        { text: 'IXÉ AÎPORU', highlight: 'new-word' },
        { text: 'pesẽ' }
      ],
      tokenBank: ['a colher', 'mesa', 'uso', 'faca', 'comida', 'eu'],
      correctSequence: ['eu', 'uso', 'a colher'],
    },
    {
      id: 'ex8',
      type: 'multiple_choice_translation',
      instruction: 'Responda ao diálogo',
      newWordBadge: true,
      character: { id: 'nonbinary', mood: 'neutral' },
      audio: repoAudio('audio/unit1-tembi-u/ex8-audio.webm', { id: 'ex8-audio' }),
      meaning: 'Como com colher',
      xp: 8,
      prompt: 'Erekarupe pesẽ pupé?',
      promptSegments: [
        { text: 'EREKARUPE', highlight: 'new-word' },
        { text: 'pesẽ pupé?' }
      ],
      choices: ['Akaru tembi\'u', 'Akaru pesẽ pupé', 'A\'useî \'y.'],
      correctChoice: 'Akaru pesẽ pupé',
    }
  ],
}
